FROM scratch

RUN \
    apt-get update && apt-get install -y \
        apache2-dev \
        autoconf \
        build-essential \
        libapr1-dev \
        libaprutil1-dev \
        libsqlite3-dev \
        libtool \
        python \
        zlib1g-dev
